# Generated by Django 4.1.5 on 2023-02-09 16:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Key for user', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='First Name', max_length=20)),
                ('last_name', models.CharField(help_text='Last Name', max_length=40)),
                ('current_position', models.CharField(help_text='Current Position', max_length=30)),
                ('new_position', models.CharField(help_text='Promotion Position', max_length=30)),
                ('current_path', models.CharField(blank=True, choices=[('m', 'Management'), ('e', 'Expert')], default='e', help_text='Current Career Path', max_length=1)),
                ('new_path', models.CharField(blank=True, choices=[('m', 'Management'), ('e', 'Expert')], default='e', help_text='New Career Path (choose even if the path is not changing)', max_length=1)),
                ('current_job', models.CharField(blank=True, choices=[('x', 'Executive'), ('m', 'Management'), ('s', 'Sales'), ('t', 'Technical'), ('p', 'Professional'), ('c', 'Client Services')], help_text='Current Job Category', max_length=1)),
                ('new_job', models.CharField(blank=True, choices=[('x', 'Executive'), ('m', 'Management'), ('s', 'Sales'), ('t', 'Technical'), ('p', 'Professional'), ('c', 'Client Services')], help_text='New Job Category (choose even if the category is not changing)', max_length=1)),
                ('current_level', models.CharField(blank=True, choices=[('e7', 'E7'), ('m6', 'M6'), ('m5', 'M5'), ('m4', 'M4'), ('m3', 'M3'), ('m2', 'M2'), ('sm5', 'SM5'), ('sm3', 'SM3'), ('s5', 'S5'), ('s4', 'S4'), ('s3', 'S3'), ('s2', 'S2'), ('s1', 'S1'), ('t5', 'T5'), ('t4', 'T4'), ('t3', 'T3'), ('t2', 'T2'), ('t1', 'T1'), ('p5', 'P5'), ('p4', 'P4'), ('p3', 'P3'), ('p2', 'P2'), ('p1', 'P1'), ('cm5', 'CSM5'), ('cm2', 'CSM2'), ('cs5', 'CS5'), ('cs4', 'CS4'), ('cs3', 'CS3'), ('cs2', 'CS2')], help_text='Current Level', max_length=3)),
                ('new_level', models.CharField(blank=True, choices=[('e7', 'E7'), ('m6', 'M6'), ('m5', 'M5'), ('m4', 'M4'), ('m3', 'M3'), ('m2', 'M2'), ('sm5', 'SM5'), ('sm3', 'SM3'), ('s5', 'S5'), ('s4', 'S4'), ('s3', 'S3'), ('s2', 'S2'), ('s1', 'S1'), ('t5', 'T5'), ('t4', 'T4'), ('t3', 'T3'), ('t2', 'T2'), ('t1', 'T1'), ('p5', 'P5'), ('p4', 'P4'), ('p3', 'P3'), ('p2', 'P2'), ('p1', 'P1'), ('cm5', 'CSM5'), ('cm2', 'CSM2'), ('cs5', 'CS5'), ('cs4', 'CS4'), ('cs3', 'CS3'), ('cs2', 'CS2')], help_text='New Level', max_length=3)),
                ('requester', models.CharField(blank=True, help_text='Not Used', max_length=1)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular review', primary_key=True, serialize=False)),
                ('review_date', models.DateField(default=datetime.datetime(2023, 2, 9, 16, 37, 28, 722166, tzinfo=datetime.timezone.utc), help_text='Date of review')),
                ('approver', models.CharField(help_text='Manager who will be approving', max_length=50)),
                ('role_info', models.TextField(help_text='Role information (please see text on the page for moreinformation).', max_length=1000)),
                ('person_info', models.TextField(help_text='Info about the person (please see text on the pagefor more information).', max_length=1000)),
                ('performance_quality', models.BooleanField(blank=True, help_text='Work Quality')),
                ('performance_goals', models.BooleanField(blank=True, help_text='Meeting Goals')),
                ('skills_require', models.BooleanField(blank=True, help_text='Required skills')),
                ('skills_compare', models.BooleanField(blank=True, help_text='Skills compared to colleagues')),
                ('values_company', models.BooleanField(blank=True, help_text='Company Values')),
                ('values_interest', models.BooleanField(blank=True, help_text='Interest in projects')),
                ('communication_appropriate', models.BooleanField(blank=True, help_text='Communicate appropriately?')),
                ('communication_respect', models.BooleanField(blank=True, help_text='Communicate with respect?')),
                ('leadership_principles', models.BooleanField(blank=True, help_text='Show leadership principles?')),
                ('leadership_motivate', models.BooleanField(blank=True, help_text='Motivate Others?')),
                ('feedback', models.TextField(help_text='Specific feedback from others', max_length=1000)),
                ('ready_for_review', models.BooleanField(blank=True, default=True, help_text='Ready for manager approval')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpReview.person')),
                ('reviewer', models.ForeignKey(help_text='Manager writing the review', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this approval', primary_key=True, serialize=False)),
                ('approval_date', models.DateField(default=datetime.datetime(2023, 2, 9, 16, 37, 28, 722166, tzinfo=datetime.timezone.utc), help_text='Date of Approval')),
                ('business_case', models.BooleanField(blank=True, help_text='Meets business requirements?')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='New Salary', max_digits=7)),
                ('currency_type', models.CharField(choices=[('gbp', 'British Pound'), ('cad', 'Canadian Dollars'), ('usd', 'US Dollars')], help_text='Currency Type', max_length=3)),
                ('variable_comp', models.CharField(help_text='Variable Compensation Element?', max_length=200)),
                ('budget', models.BooleanField(blank=True, help_text='Budget available?')),
                ('equity', models.BooleanField(blank=True, help_text='Trigger Equity or LTIP?')),
                ('next_increase', models.BooleanField(blank=True, help_text='Exclude from next increase?')),
                ('final_approver', models.CharField(help_text='Final Approver', max_length=50)),
                ('approved', models.BooleanField(blank=True, help_text='Approved?')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpReview.person')),
                ('review', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EmpReview.review')),
            ],
        ),
    ]
