# Generated by Django 4.1.5 on 2023-02-09 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mgr_first_name',
            field=models.CharField(help_text='Manager First Name', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='mgr_last_name',
            field=models.CharField(help_text='Manager Last Name', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='approval_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 9, 18, 2, 1, 589492, tzinfo=datetime.timezone.utc), help_text='Date of Approval'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 9, 18, 2, 1, 588503, tzinfo=datetime.timezone.utc), help_text='Date of review'),
        ),
    ]
