# Generated by Django 4.1.5 on 2023-02-22 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpReview', '0004_alter_approval_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 21, 4, 24, 766218, tzinfo=datetime.timezone.utc), help_text='Date of Approval'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='final_approver',
            field=models.ForeignKey(help_text='Final Approver', on_delete=django.db.models.deletion.DO_NOTHING, to='EmpReview.employee'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EmpReview.person'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='review',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EmpReview.review'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='managerId',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='employee',
            name='userId',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='review',
            name='approver',
            field=models.ForeignKey(help_text='Manager who will be approving', max_length=50, on_delete=django.db.models.deletion.DO_NOTHING, related_name='appover', to='EmpReview.employee'),
        ),
        migrations.AlterField(
            model_name='review',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='EmpReview.person'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 21, 4, 24, 765221, tzinfo=datetime.timezone.utc), help_text='Date of review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(help_text='Manager writing the review', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to='EmpReview.employee'),
        ),
    ]
