# Generated by Django 4.1.5 on 2023-03-03 15:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmpReview', '0008_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('user__last_name', 'user__first_name')},
        ),
        migrations.AlterField(
            model_name='approval',
            name='approval_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 15, 49, 51, 101908, tzinfo=datetime.timezone.utc), help_text='Date of Approval'),
        ),
        migrations.AlterField(
            model_name='person',
            name='mgr_name',
            field=models.ForeignKey(default=None, help_text='Manager Name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Manager_Name', to='EmpReview.employee'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 3, 15, 49, 51, 101908, tzinfo=datetime.timezone.utc), help_text='Date of review'),
        ),
    ]
