# Generated by Django 4.1.5 on 2023-03-06 00:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empreview', '0010_alter_approval_approval_date_alter_review_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 6, 0, 46, 39, 786791, tzinfo=datetime.timezone.utc), help_text='Date of Approval'),
        ),
        migrations.AlterField(
            model_name='person',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='empreview.employee'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 6, 0, 46, 39, 785794, tzinfo=datetime.timezone.utc), help_text='Date of review'),
        ),
    ]
